likelion-plus/counting-stars-13

- src/layout/Header.tsx
- src/pages/Search.tsx
검색페이지 html/css 마크업
Resolves: #30
> markup: 검색페이지 html/css 마크업

- src/pages/Login.tsx
- src/utils/debounce.tsx
- Login page 기능 추가
- debounce 기능 추가
> [기능 구현] Login page 기능 추가, debounce 기능 추가

- src/layout/Header.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/pages/Search.tsx
- src/store/useLogin.ts
- src/store/useUserInfo.ts
- src/utils/loginReg.tsx
Login페이지
1. 로그인하면 값이 로컬스토리지에 올라감
2. 로그인하면 Header의 메뉴가 바뀜
3. 로그아웃 기능
4. useUserInfo.ts 파일 생성. 로그인하면 해당 유저 값을 쥬스텐드로 올림
5. header에 메뉴 link 변경
Join페이지
1. 회원가입 값 저장
2. 유효성 검사
3. loginReg.tsx 유효성 검사 파일에 이메일, 핸드폰번호 유효성검사 기능 추가
> feat: Login페이지, Join페이지 기능추가

- src/layout/Header.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
header에 authorization 추가, header에 로그인 유저 값 보내기
> header에 authorization 추가, header에 로그인 유저 값 보내기

- src/pages/Join.tsx
- src/pages/Login.tsx
- feat: Join페이지, 회원가입 기능 완성
- test: login페이지, Authorization을 헤더에 추가하는 코드 삭제
> Join페이지, 회원가입 기능 완성, login페이지 테스트코드 삭제

- src/components/Detail/DetailProductOption.tsx
- src/components/Detail/DetailProductResult.tsx
- src/components/Detail/DetailProductSelect.tsx
- src/components/Detail/ProductQuantity.tsx
- src/styles/tailwind.css
> [기능 구현] 상세 페이지 상품별 옵션 렌더링 및 카운트 기능 구현, 개별 카운트 기능 구현 중

- src/layout/Header.tsx
- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/store/useUserInfo.ts
- src/utils/loginReg.tsx
- Join 페이지 유효성 검사 기능
- 모두 동의 체크박스 기능
- Edit 페이지 회원정보 가져오기
- 회원정보수정 기능
- Login 페이지 로그인 유효성 검사
- 로그아웃시 로그아웃 알림 기능
- 유효성 검사 정규식 수정
- 타입스크립트 `emailAgree: boolean;` 추가
> Login page, Join page, EditPage

- README.md
- src/components/Detail/DetailImg.tsx
- src/components/Detail/DetailProductOption.tsx
- src/components/Detail/DetailProductSelect.tsx
- src/pages/Detail.tsx
> [기능 구현] 상세 페이지 옵션별 개별 카운트, 개별 금액, 총 금액 합산, 개수 합산 기능 구현 및 api 서버 리드미 설명

- src/components/EditMember/phoneNumber.tsx
- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/store/usePhoneNumber.ts
feat: EditMember 페이지, 전화번호 값 넣기
- 전화번호 값 넣기
- 번호 값 zustand파일 생성
- 번호 값 앞자리,중간자리,끝자리로 나누는 함수 분리
feat: Join 페이지 기능추가
- 값이 없으면 해당 인풋으로 이동
- 이메일 확인버튼 -> 중복확인 으로 변경
- 중복확인 누르면 이메일 유효성검사하고 이메일 중복 검사하기
- (이메일 형식) 지우기
- 이름 길이 20자 이하로 만들기
- 비밀번호 확인, 휴대전화 형식 - 버튼누르기전에 확인가능하게 만들기
- 필수동의란을 확인해주세요 알림창 띄여쓰기
feat: Login 페이지 인풋값 초기화 기능
- 인풋값 초기화 기능
> EditMember 페이지, Join 페이지, Login 페이지 기능추가

- src/pages/EditMember.tsx
토큰 값, 아이디값 함수로 수정
related to: #68
> chore: 토큰 값, 아이디값 함수로 수정

- src/layout/Header.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
Login page, join page, header page 기능수정
> Login page, join page, header page

- src/components/EditMember/phoneNumber.tsx
- src/components/Login,Join/EmailCheckButton.tsx
- src/components/Wish/MiniButton.tsx
- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/pages/MyShopping.tsx
- src/pages/Order.tsx
- src/pages/Wish.tsx
- src/routes.tsx
EditMember, Join, Wish, Order 페이지 생성 및 수정
> EditMember, Join, Wish, Order 페이지 생성 및 수정

- src/components/Detail/DetailProductSelect.tsx
- src/layout/Header.tsx
- src/pages/MyCart.tsx
- src/pages/Shop.tsx
- src/vite-env.d.ts
related to: #78 #89 #95 #99 #100
> [기능 구현] 장바구니 페이지 렌더링 및 합산, 개별, 전체 삭제 및 쇼핑 페이지 전체 목록 불러오기 등

- src/components/EditMember/EditAddress.tsx
- src/pages/EditMember.tsx
- src/pages/MyOrder.tsx
- src/pages/Order.tsx
- src/store/useEditMemberInfo.ts
- src/store/useMyOrderInfo.ts
- src/store/useOrderUserInfo.ts
- EditMember 페이지 마크업 변경, 상태 zustand로 올리기
- Order 페이지 html/css 마크업, 주소쓰는 곳 컴포넌트 분리
- MyOrder 페이지, 주문목록 불러오기
> EditMember, Order, MyOrder 마크업 및 기능구현 진행했습니다.

- src/components/MyOrder/OrderItem.tsx
- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/MyOrder.tsx
- src/pages/Order.tsx
- src/vite-env.d.ts
- MyOrder 페이지, 날짜별로 주문 목록 리스트로 출력
- 필요없는 주석 삭제
> [기능구현] MyOrder 페이지 - 날짜별로 주문 목록 리스트로 출력

- src/components/MyOrder/OrderItem.tsx
- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/Login.tsx
- src/pages/MyOrder.tsx
- src/store/useMyOrderInfo.ts
- MyOrder 페이지 타입 에러 해결
- Login 페이지 console.log 삭제
fixes: #111
> chore: MyOrder 페이지 타입 에러 해결

- src/components/MyOrder/OrderItem.tsx
- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/MyOrder.tsx
> feat: MyOrder 페이지, 주문 상태 필러팅 기능 구현

- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/Login.tsx
- src/pages/MyOrder.tsx
- src/store/useMyOrderInfo.ts
- loginPage, console.log 삭제
- MyOrder 페이지, 날짜 기간으로 주문조회
> Login page, MyOrder page

- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/MyOrder.tsx
- MyOrder 페이지, 날짜 기간 아무값도 없을 때 전체 출력
- 기간 하나만 정해도 주문 리스트 출력
fixes: #111
> feat: MyOrder 페이지, 날짜 기간 기능 수정

- package-lock.json
- package.json
- src/pages/MyOrder.tsx
- moment 패키지 설치
- MyOrder 페이지 날짜 제한 기능
fixes: #111
> feat: MyOrder 페이지 날짜 제한 기능

- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/Login.tsx
- src/pages/MyOrder.tsx
- src/pages/MyOrderDetail.tsx
- src/routes.tsx
- 기간 검색시 3개월씩만 검색하는 기능
- 주문조회 최근 3개월 리스트만 불러오기 기능
- MyOrderDetail 페이지 마크업
- loginPage 이메일 찾기, 비밀번호 찾기 기능 구현 중 모달 띄우기
- MyOrder 페이지, 최근부터 3개월까지만 리스트 출력
> [기능구현, 마크업]MyOrderDetail , MyOrder , loginPage 

- src/pages/MyOrderDetail.tsx
MyOrder 페이지, html,css 마크업
resolves: #138
> markup: MyOrder 페이지, html,css 마크업

- src/components/MyOrder/OrderItem.tsx
- src/components/MyOrder/OrderItemDetail.tsx
- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/pages/MyOrder.tsx
- src/pages/MyOrderDetail.tsx
- src/routes.tsx
- MyOrderDetail 페이지, 주문 상세 리스트, 가격 출력
- 루트에 id값 추가
- MyOrder 페이지에 상품 누르면 해당 주문 상세페이지로 이동
- 진행했던 페이지 Axios 수정
> [기능 구현] MyOrderDetail 페이지, 주문 상세 리스트, 가격 출력

- src/pages/Join.tsx
- src/pages/MyOrderDetail.tsx
- src/utils/useDeliveryState.tsx
-  MyOrderDetail 페이지 구매자 이름 불러오기
-  상품 배송 상태 불러오기
- useDeliveryState 함수 분리
- Join 페이지 주석 정리
-  MyOrder 배송 상태 버그 해결
> [기능 구현] MyOrderDetail 페이지 

- src/pages/MyCart.tsx
- src/pages/Wish.tsx
> fix: build 문제 해결

- src/App.tsx
- src/pages/MyOrderDetail.tsx
- src/utils/AUTH_TOKEN.ts
- src/utils/TokenRefresher.tsx
- access 토큰 재발행 기능
- MyOrderDetail 페이지, 옵션값, 주소값 설정
> [기능 구현] access 토큰 재발행 기능, MyOrderDetail 페이지, 옵션값, 주소값 설정

- src/pages/EditMember.tsx
- src/pages/MyOrderDetail.tsx
> chore: 코드 정리

- src/pages/MyOrder.tsx
- src/pages/MyOrderDetail.tsx
- src/vite-env.d.ts
> docs: MyOrderDetail 수정

- src/store/useMyOrderInfo.ts
> chore: 에러 해결

- src/pages/MyOrderDetail.tsx
- src/vite-env.d.ts
MyOrderDetail 페이지, 전화번호, 배송메세지 추가
fixes: #157
> chore: MyOrderDetail 페이지, 전화번호, 배송메세지 추가

- src/pages/MyOrderDetail.tsx
> chore: 콘솔 삭제

- src/pages/EditMember.tsx
- src/pages/Join.tsx
- src/pages/Login.tsx
- src/store/useJoinToLogin.ts
- 로그인 안했으면 접근 못하게 막기
- maxLength 추가
> chore: Join, Login, EditMember 페이지 수정

- src/pages/EditMember.tsx
- src/pages/Login.tsx
- src/pages/MyShopping.tsx
- admin 계정 관리자로 표시
- loginPage 코드 정리
> admin 계정 관리자로 표시
